# Generated by Django 2.1.1 on 2018-09-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
